/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/playground/': RouteRecordInfo<'/playground/', '/playground', Record<never, never>, Record<never, never>>,
    '/playground/salary-calculator-page': RouteRecordInfo<'/playground/salary-calculator-page', '/playground/salary-calculator-page', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/a-note': RouteRecordInfo<'/posts/a-note', '/posts/a-note', Record<never, never>, Record<never, never>>,
    '/posts/component-library-analysis': RouteRecordInfo<'/posts/component-library-analysis', '/posts/component-library-analysis', Record<never, never>, Record<never, never>>,
    '/posts/first-post': RouteRecordInfo<'/posts/first-post', '/posts/first-post', Record<never, never>, Record<never, never>>,
    '/posts/mac-config': RouteRecordInfo<'/posts/mac-config', '/posts/mac-config', Record<never, never>, Record<never, never>>,
    '/posts/package-manager': RouteRecordInfo<'/posts/package-manager', '/posts/package-manager', Record<never, never>, Record<never, never>>,
    '/posts/react-event': RouteRecordInfo<'/posts/react-event', '/posts/react-event', Record<never, never>, Record<never, never>>,
    '/posts/react-fiber': RouteRecordInfo<'/posts/react-fiber', '/posts/react-fiber', Record<never, never>, Record<never, never>>,
    '/posts/react-hook-form-type': RouteRecordInfo<'/posts/react-hook-form-type', '/posts/react-hook-form-type', Record<never, never>, Record<never, never>>,
    '/posts/tankstank-query': RouteRecordInfo<'/posts/tankstank-query', '/posts/tankstank-query', Record<never, never>, Record<never, never>>,
    '/posts/vue-reactive-1': RouteRecordInfo<'/posts/vue-reactive-1', '/posts/vue-reactive-1', Record<never, never>, Record<never, never>>,
    '/posts/web-render-types': RouteRecordInfo<'/posts/web-render-types', '/posts/web-render-types', Record<never, never>, Record<never, never>>,
  }
}
