name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  # 第一个 Job：安装依赖和构建
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build project
        run: pnpm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # 第二个 Job：Docker 镜像构建和推送，依赖于第一个 job
  docker:
    runs-on: ubuntu-latest
    needs: build # 依赖于 build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Login to Tencent Cloud Registry
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} ccr.ccs.tencentyun.com --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t heggria:latest .
          docker tag heggria ccr.ccs.tencentyun.com/heggria/blog:latest

      - name: Push Docker image
        run: |
          docker push ccr.ccs.tencentyun.com/heggria/blog:latest

  # 第三个 Job：部署到服务器，依赖于 Docker 镜像构建完成
  deploy:
    runs-on: ubuntu-latest
    needs: docker # 依赖 docker job
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd ~ && sh heggria.site.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
