name: Docker Image CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      # 安装依赖，并缓存 pnpm 缓存以提升构建速度
      - name: install pnpm
        run: npm i -g pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      # 打包项目
      - name: build project
        run: pnpm run build

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ccr.ccs.tencentyun.com
          docker build -t heggria:latest .
          docker tag heggria ccr.ccs.tencentyun.com/heggria/blog:latest
          docker push ccr.ccs.tencentyun.com/heggria/blog:latest

      # SSH 登录并执行脚本
      - name: SSH and pull new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/heggria.site
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ccr.ccs.tencentyun.com
            docker-compose pull
            docker-compose up -d
