name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 安装 SSH 客户端并测试
    - name: Install and Test SSH
      run: |
        sudo apt-get update && sudo apt-get install -y openssh-client
        ssh -V  # 测试 SSH 是否安装成功

    # 设置 SSH 密钥
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}

    # 测试 SSH 连接
    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$IP echo "SSH connected successfully"
      env:
        USER: ${{ secrets.TENCENT_CLOUD_USER }}
        IP: ${{ secrets.TENCENT_CLOUD_IP }}

    # 部署到腾讯云
    - name: Deploy to Tencent Cloud
      env:
        USER: ${{ secrets.TENCENT_CLOUD_USER }}
        IP: ${{ secrets.TENCENT_CLOUD_IP }}
        PATH: ${{ secrets.TENCENT_CLOUD_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$IP << 'EOF'
          cd $PATH &&
          git pull origin main &&
          npm install &&
          npm run build
        EOF
